### ISSUE TITLE
Outputs a black image

### ISSUE THREAD

**Issue by Drahsid** [yui0/waifu2x-ocl#1]
When running the program, the output is a black image with the exact color of (1, 1, 0).

**Comment by yui0** [comment]
GPGPU is very sensitive and the environment affects the results. Please tell me about your environment. In my environment, Berry Linux and macOS on Mac Pro, make this program a success.

**Comment by Drahsid** [comment]
I compiled the program for Windows 10 Build 17134.112

**Comment by amayra** [comment]
how did you compiled this ?

**Comment by yui0** [comment]
I compiled this program on Windows 10 with Visual Studio 2017.
And it was successfully tested.
Please try the new version.

**Comment by Drahsid** [comment]
Looks like it is working now. Thank you.

**Comment by yui0** [comment]
Thank you for your information!
